import type { FileRouteTypes } from "@/routeTree.gen";

export type PageDefinition = {
  path: FileRouteTypes["to"];
  title: string;
  section: string;
  description: string;
};
export const pages = [
  {
    path: "/",
    title: "Bienvenue sur Pokedata",
    section: "Accueil",
    description: "Explorez les univers du projet et parcourez les pages prévues.",
  },
  {
    path: "/explorer",
    title: "Explorer",
    section: "Explorer",
    description: "Pokédex, encyclopédie et recherche.",
  },
  {
    path: "/strategie",
    title: "Stratégie",
    section: "Stratégie",
    description: "Formats, équipes et analyse compétitive.",
  },
  {
    path: "/collection",
    title: "Collection",
    section: "Collection",
    description: "Pokémon, cartes et suivi de collection.",
  },
  {
    path: "/mini-jeux",
    title: "Mini-jeux",
    section: "Mini-jeux",
    description: "Défis, quiz et jeux de connaissance.",
  },
  {
    path: "/communaute",
    title: "Communauté",
    section: "Communauté",
    description: "Discussions et créations des membres.",
  },
  {
    path: "/outils",
    title: "Outils",
    section: "Outils",
    description: "Calculateurs et outils pour préparer votre aventure.",
  },
  {
    path: "/moi",
    title: "Mon espace",
    section: "Mon espace",
    description: "Équipes, collections et progression personnelles.",
  },
  {
    path: "/pokedex",
    title: "Pokédex national",
    section: "Explorer",
    description: "Espace prévu pour pokédex national.",
  },
  {
    path: "/encyclopedie",
    title: "Encyclopédie",
    section: "Explorer",
    description: "Espace prévu pour encyclopédie.",
  },
  {
    path: "/recherche",
    title: "Recherche globale",
    section: "Explorer",
    description: "Espace prévu pour recherche globale.",
  },
  {
    path: "/pokedex/regionaux",
    title: "Pokédex régionaux",
    section: "Explorer",
    description: "Espace prévu pour pokédex régionaux.",
  },
  {
    path: "/pokedex/regionaux/$pokedexId",
    title: "Détail du Pokédex régional",
    section: "Explorer",
    description: "Espace prévu pour détail du pokédex régional.",
  },
  {
    path: "/pokedex/$pokemonId",
    title: "Fiche Pokémon",
    section: "Explorer",
    description: "Espace prévu pour fiche pokémon.",
  },
  {
    path: "/pokedex/$pokemonId/formes",
    title: "Formes et variétés",
    section: "Explorer",
    description: "Espace prévu pour formes et variétés.",
  },
  {
    path: "/pokedex/$pokemonId/evolutions",
    title: "Évolutions",
    section: "Explorer",
    description: "Espace prévu pour évolutions.",
  },
  {
    path: "/pokedex/$pokemonId/attaques",
    title: "Attaques apprises",
    section: "Explorer",
    description: "Espace prévu pour attaques apprises.",
  },
  {
    path: "/pokedex/$pokemonId/rencontres",
    title: "Rencontres",
    section: "Explorer",
    description: "Espace prévu pour rencontres.",
  },
  {
    path: "/pokedex/$pokemonId/reproduction",
    title: "Reproduction",
    section: "Explorer",
    description: "Espace prévu pour reproduction.",
  },
  {
    path: "/pokedex/$pokemonId/medias",
    title: "Images et cris",
    section: "Explorer",
    description: "Espace prévu pour images et cris.",
  },
  {
    path: "/pokedex/$pokemonId/historique",
    title: "Données par génération",
    section: "Explorer",
    description: "Espace prévu pour données par génération.",
  },
  {
    path: "/encyclopedie/attaques",
    title: "Attaques",
    section: "Explorer",
    description: "Espace prévu pour attaques.",
  },
  {
    path: "/encyclopedie/attaques/$attaqueId",
    title: "Détail : Attaques",
    section: "Explorer",
    description: "Espace prévu pour détail : attaques.",
  },
  {
    path: "/encyclopedie/talents",
    title: "Talents",
    section: "Explorer",
    description: "Espace prévu pour talents.",
  },
  {
    path: "/encyclopedie/talents/$talentId",
    title: "Détail : Talents",
    section: "Explorer",
    description: "Espace prévu pour détail : talents.",
  },
  {
    path: "/encyclopedie/objets",
    title: "Objets",
    section: "Explorer",
    description: "Espace prévu pour objets.",
  },
  {
    path: "/encyclopedie/objets/$objetId",
    title: "Détail : Objets",
    section: "Explorer",
    description: "Espace prévu pour détail : objets.",
  },
  {
    path: "/encyclopedie/baies",
    title: "Baies",
    section: "Explorer",
    description: "Espace prévu pour baies.",
  },
  {
    path: "/encyclopedie/baies/$baieId",
    title: "Détail : Baies",
    section: "Explorer",
    description: "Espace prévu pour détail : baies.",
  },
  {
    path: "/encyclopedie/types",
    title: "Table des types",
    section: "Explorer",
    description:
      "Efficacité de chaque type d'attaque contre chaque type défenseur, par génération.",
  },
  {
    path: "/encyclopedie/types/$typeId",
    title: "Détail : Types",
    section: "Explorer",
    description: "Espace prévu pour détail : types.",
  },
  {
    path: "/encyclopedie/mecaniques",
    title: "Mécaniques",
    section: "Explorer",
    description: "Espace prévu pour mécaniques.",
  },
  {
    path: "/encyclopedie/mecaniques/$slug",
    title: "Détail : Mécaniques",
    section: "Explorer",
    description: "Espace prévu pour détail : mécaniques.",
  },
  {
    path: "/strategie/formats",
    title: "Formats",
    section: "Stratégie",
    description: "Espace prévu pour formats.",
  },
  {
    path: "/strategie/formats/$formatId/usages",
    title: "Statistiques d’usage",
    section: "Stratégie",
    description: "Espace prévu pour statistiques d’usage.",
  },
  {
    path: "/strategie/formats/$formatId/pokemon/$pokemonId",
    title: "Analyse du Pokémon",
    section: "Stratégie",
    description: "Espace prévu pour analyse du pokémon.",
  },
  {
    path: "/strategie/formats/$formatId/cores",
    title: "Duos et noyaux d’équipe",
    section: "Stratégie",
    description: "Espace prévu pour duos et noyaux d’équipe.",
  },
  {
    path: "/strategie/formats/$formatId/archetypes",
    title: "Archétypes",
    section: "Stratégie",
    description: "Espace prévu pour archétypes.",
  },
  {
    path: "/equipes",
    title: "Équipes publiques",
    section: "Stratégie",
    description: "Espace prévu pour équipes publiques.",
  },
  {
    path: "/equipes/$equipeId",
    title: "Équipe partagée",
    section: "Stratégie",
    description: "Espace prévu pour équipe partagée.",
  },
  {
    path: "/outils/constructeur-equipe",
    title: "Constructeur d’équipe",
    section: "Outils",
    description: "Espace prévu pour constructeur d’équipe.",
  },
  {
    path: "/outils/degats",
    title: "Calculateur de dégâts",
    section: "Outils",
    description: "Espace prévu pour calculateur de dégâts.",
  },
  {
    path: "/outils/couverture",
    title: "Couverture des types",
    section: "Outils",
    description: "Espace prévu pour couverture des types.",
  },
  {
    path: "/outils/vitesse",
    title: "Comparateur de vitesse",
    section: "Outils",
    description: "Espace prévu pour comparateur de vitesse.",
  },
  {
    path: "/outils/statistiques",
    title: "Calculateur de statistiques",
    section: "Outils",
    description: "Espace prévu pour calculateur de statistiques.",
  },
  {
    path: "/outils/comparateur",
    title: "Comparateur de Pokémon",
    section: "Outils",
    description: "Espace prévu pour comparateur de pokémon.",
  },
  {
    path: "/outils/capture",
    title: "Calculateur de capture",
    section: "Outils",
    description: "Espace prévu pour calculateur de capture.",
  },
  {
    path: "/outils/reproduction",
    title: "Outil de reproduction",
    section: "Outils",
    description: "Espace prévu pour outil de reproduction.",
  },
  {
    path: "/outils/shiny",
    title: "Probabilités chromatiques",
    section: "Outils",
    description: "Espace prévu pour probabilités chromatiques.",
  },
  {
    path: "/outils/evolutions",
    title: "Assistant d’évolution",
    section: "Outils",
    description: "Espace prévu pour assistant d’évolution.",
  },
  {
    path: "/outils/fichiers",
    title: "Gestionnaire de fichiers",
    section: "Outils",
    description: "Espace de fichiers avec dossiers, imports locaux et aperçus.",
  },
  {
    path: "/outils/transferts",
    title: "Compatibilité des transferts",
    section: "Outils",
    description: "Espace prévu pour compatibilité des transferts.",
  },
  {
    path: "/collection/modeles",
    title: "Modèles de collection",
    section: "Collection",
    description: "Espace prévu pour modèles de collection.",
  },
  {
    path: "/cartes",
    title: "Catalogue de cartes",
    section: "Collection",
    description: "Espace prévu pour catalogue de cartes.",
  },
  {
    path: "/cartes/$carteId",
    title: "Fiche de carte",
    section: "Collection",
    description: "Espace prévu pour fiche de carte.",
  },
  {
    path: "/extensions",
    title: "Extensions du JCC",
    section: "Collection",
    description: "Espace prévu pour extensions du jcc.",
  },
  {
    path: "/extensions/$extensionId",
    title: "Détail de l’extension",
    section: "Collection",
    description: "Espace prévu pour détail de l’extension.",
  },
  {
    path: "/collections/$partageId",
    title: "Collection partagée",
    section: "Collection",
    description: "Espace prévu pour collection partagée.",
  },
  {
    path: "/mini-jeux/defi-du-jour",
    title: "Défi du jour",
    section: "Mini-jeux",
    description: "Espace prévu pour défi du jour.",
  },
  {
    path: "/mini-jeux/devine-pokemon",
    title: "Devine le Pokémon",
    section: "Mini-jeux",
    description: "Espace prévu pour devine le pokémon.",
  },
  {
    path: "/mini-jeux/silhouettes",
    title: "Silhouettes",
    section: "Mini-jeux",
    description: "Espace prévu pour silhouettes.",
  },
  {
    path: "/mini-jeux/cris",
    title: "Reconnais le cri",
    section: "Mini-jeux",
    description: "Espace prévu pour reconnais le cri.",
  },
  {
    path: "/mini-jeux/types",
    title: "Quiz des types",
    section: "Mini-jeux",
    description: "Espace prévu pour quiz des types.",
  },
  {
    path: "/mini-jeux/evolutions",
    title: "Chaînes d’évolution",
    section: "Mini-jeux",
    description: "Espace prévu pour chaînes d’évolution.",
  },
  {
    path: "/mini-jeux/plus-ou-moins",
    title: "Plus ou moins",
    section: "Mini-jeux",
    description: "Espace prévu pour plus ou moins.",
  },
  {
    path: "/mini-jeux/quiz",
    title: "Quiz",
    section: "Mini-jeux",
    description: "Espace prévu pour quiz.",
  },
  {
    path: "/mini-jeux/quiz/$quizId",
    title: "Jouer au quiz",
    section: "Mini-jeux",
    description: "Espace prévu pour jouer au quiz.",
  },
  {
    path: "/mini-jeux/grille",
    title: "Grille Pokémon",
    section: "Mini-jeux",
    description: "Espace prévu pour grille pokémon.",
  },
  {
    path: "/mini-jeux/memory",
    title: "Memory",
    section: "Mini-jeux",
    description: "Espace prévu pour memory.",
  },
  {
    path: "/mini-jeux/classements",
    title: "Classements des mini-jeux",
    section: "Mini-jeux",
    description: "Espace prévu pour classements des mini-jeux.",
  },
  {
    path: "/communaute/discussions",
    title: "Discussions",
    section: "Communauté",
    description: "Espace prévu pour discussions.",
  },
  {
    path: "/communaute/discussions/$discussionId",
    title: "Discussion",
    section: "Communauté",
    description: "Espace prévu pour discussion.",
  },
  {
    path: "/membres/$pseudo",
    title: "Profil public",
    section: "Communauté",
    description: "Espace prévu pour profil public.",
  },
  {
    path: "/guides",
    title: "Tous les guides",
    section: "Communauté",
    description: "Espace prévu pour tous les guides.",
  },
  {
    path: "/guides/$slug",
    title: "Lire un guide",
    section: "Communauté",
    description: "Espace prévu pour lire un guide.",
  },
  {
    path: "/actualites",
    title: "Actualités",
    section: "Communauté",
    description: "Espace prévu pour actualités.",
  },
  {
    path: "/actualites/$slug",
    title: "Lire une actualité",
    section: "Communauté",
    description: "Espace prévu pour lire une actualité.",
  },
  {
    path: "/moi/equipes",
    title: "Mes équipes",
    section: "Mon espace",
    description: "Espace prévu pour mes équipes.",
  },
  {
    path: "/moi/equipes/$equipeId/modifier",
    title: "Modifier mon équipe",
    section: "Mon espace",
    description: "Espace prévu pour modifier mon équipe.",
  },
  {
    path: "/moi/collections",
    title: "Mes collections",
    section: "Mon espace",
    description: "Espace prévu pour mes collections.",
  },
  {
    path: "/moi/collections/$collectionId",
    title: "Ma collection",
    section: "Mon espace",
    description: "Espace prévu pour ma collection.",
  },
  {
    path: "/moi/classeurs",
    title: "Mes classeurs",
    section: "Mon espace",
    description: "Espace prévu pour mes classeurs.",
  },
  {
    path: "/moi/classeurs/$classeurId",
    title: "Mon classeur",
    section: "Mon espace",
    description: "Espace prévu pour mon classeur.",
  },
  {
    path: "/moi/chasses",
    title: "Mes chasses",
    section: "Mon espace",
    description: "Espace prévu pour mes chasses.",
  },
  {
    path: "/moi/chasses/$chasseId",
    title: "Ma chasse",
    section: "Mon espace",
    description: "Espace prévu pour ma chasse.",
  },
  {
    path: "/moi/souhaits",
    title: "Mes souhaits",
    section: "Mon espace",
    description: "Espace prévu pour mes souhaits.",
  },
  {
    path: "/moi/doublons",
    title: "Mes doublons",
    section: "Mon espace",
    description: "Espace prévu pour mes doublons.",
  },
  {
    path: "/moi/favoris",
    title: "Mes favoris",
    section: "Mon espace",
    description: "Espace prévu pour mes favoris.",
  },
  {
    path: "/moi/progression",
    title: "Ma progression",
    section: "Mon espace",
    description: "Espace prévu pour ma progression.",
  },
  {
    path: "/moi/historique",
    title: "Mon historique",
    section: "Mon espace",
    description: "Espace prévu pour mon historique.",
  },
  {
    path: "/moi/notifications",
    title: "Notifications",
    section: "Mon espace",
    description: "Espace prévu pour notifications.",
  },
  {
    path: "/moi/parametres",
    title: "Paramètres du compte",
    section: "Mon espace",
    description: "Espace prévu pour paramètres du compte.",
  },
  {
    path: "/plan-du-site",
    title: "Plan du site",
    section: "Accueil",
    description: "Toutes les pages prévues, y compris les pages privées et les fiches de détail.",
  },
] as const satisfies readonly PageDefinition[];
export const sections = [
  {
    title: "Explorer",
    path: "/explorer",
    description: "Pokédex, encyclopédie et recherche.",
  },
  {
    title: "Stratégie",
    path: "/strategie",
    description: "Formats, équipes et analyse compétitive.",
  },
  {
    title: "Collection",
    path: "/collection",
    description: "Pokémon, cartes et suivi de collection.",
  },
  {
    title: "Mini-jeux",
    path: "/mini-jeux",
    description: "Défis, quiz et jeux de connaissance.",
  },
  {
    title: "Communauté",
    path: "/communaute",
    description: "Discussions et créations des membres.",
  },
  {
    title: "Outils",
    path: "/outils",
    description: "Calculateurs et outils pour préparer votre aventure.",
  },
  {
    title: "Mon espace",
    path: "/moi",
    description: "Équipes, collections et progression personnelles.",
  },
] as const;
export const exampleParams = {
  pokemonId: "pikachu",
  pokedexId: "kanto",
  attaqueId: "tonnerre",
  talentId: "statik",
  objetId: "potion",
  baieId: "oran",
  typeId: "electrik",
  slug: "exemple",
  formatId: "vgc-exemple",
  equipeId: "exemple",
  carteId: "exemple",
  extensionId: "exemple",
  partageId: "exemple",
  quizId: "exemple",
  discussionId: "exemple",
  pseudo: "dresseur",
  collectionId: "exemple",
  classeurId: "exemple",
  chasseId: "exemple",
};
